### ISSUE TITLE
Problem of "no do" case

### ISSUE THREAD

**Issue by nallwhy** [definject/definject#3]
When you change the code like below and run your test, `CompileError` happens at "no do" case.
(or just run `$ env MIX_ENV=dev mix test`)

And it means that error will happen on other environments except 'test'.

```elixir
  # definject.ex:70

  defp do_definject(head, body_and_resq, %Macro.Env{} = env) do
    alias Definject.Inject

    original =
      quote do
        def unquote(head), unquote(body_and_resq)
      end

    # if Application.get_env(:definject, :enable, Mix.env() == :test) do
    #   Inject.inject_function(head, body_and_resq, env)
    #   |> trace(original, env)
    # else
      original
    # end
  end
```

```
== Compilation error in file test/use_cases/no_do_test.exs ==
** (CompileError) test/use_cases/no_do_test.exs:6: missing :do option in "def"
    test/use_cases/no_do_test.exs:6: (module)
    test/use_cases/no_do_test.exs:5: (module)
    (stdlib 3.13) erl_eval.erl:680: :erl_eval.do_apply/6
    (elixir 1.10.4) lib/kernel/parallel_compiler.ex:396: Kernel.ParallelCompiler.require_file/2
    (elixir 1.10.4) lib/kernel/parallel_compiler.ex:306: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7
```

**Comment by jechol** [comment]
@nallwhy Thanks for your report. Bug was reproducible on Elixir >= 1.10.4 and has been fixed https://github.com/definject/definject/commit/2e08ad3134acd73eb752b2f1d5c86e97c41602f2.
